Fix path to scarb toml in declare (#1081)
<!-- Reference any GitHub issues resolved by this PR -->

## Introduced changes

<!-- A brief description of the changes -->

- it seems that after recent scarb metadata bump the manifest path is
sometimes ommited in declare, causing errors:
```
command: declare
error: Failed to obtain scarb metadata: `scarb metadata` exited with error

stdout:
{"type":"error","message":"failed to read manifest at: /Users/wojciech/git-repos/starkware/starknet.swift/Scarb.toml\n\nCaused by:\n    No such file or directory (os error 2)"}

stderr:
```

this PR fixes this problem.

## Checklist

<!-- Make sure all of these are complete -->

- [X] Linked relevant issue
- [X] Updated relevant documentation
- [X] Added relevant tests
- [X] Performed self-review of the code
- [X] Added changes to `CHANGELOG.md`