Proper sncast error handling (#4338)
<!-- Reference any GitHub issues resolved by this PR -->

Closes #3957 

## Introduced changes

<!-- A brief description of the changes -->

- Non-panic errors no longer bypass foundry UI, meaning they will be
correctly displayed in line with human-readable / json format.
  So instead of: 
  ```
Error: Failed to load global config at
/Users/runner/.config/starknet-foundry/snfoundry.toml

  Caused by:
Failed to parse field `block-explorer`: unknown variant `Starkscan`,
expected one of `Voyager`, `StarkScan`, `ViewBlock`, `OkLink`
  ```
  we have:
  - in human readable format:
  ```
  Command: show-config
Error: Failed to load global config at
/Users/runner/.config/starknet-foundry/snfoundry.toml
  
  Caused by:
Failed to parse field `block-explorer`: unknown variant `Starkscan`,
expected one of `Voyager`, `StarkScan`, `ViewBlock`, `OkLink`
  ```
  - in json format:
  ```
{"command":"show-config","error":"Failed to load global config at
/Users/runner/.config/starknet-foundry/snfoundry.toml: Failed to parse
field `block-explorer`: unknown variant `Starkscan`, expected one of
`Voyager`, `StarkScan`, `ViewBlock`, `OkLink`","type":"error"}
  ```
- Build failures now return command errors instead of panicking.
- In command errors, `command` tag now universally displays a full
command path (`get tx-status`, `account import`)
- previously in some cases, only top-level command name was shown, e.g.
`get`, `account`

## Checklist

<!-- Make sure all of these are complete -->

- [x] Linked relevant issue
- [ ] Updated relevant documentation
- [x] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

---------

Co-authored-by: Franciszek Job <54181625+franciszekjob@users.noreply.github.com>