Fix panic when exact is used without test filter (#4168)
## Introduced changes

Make sure test filter is required when using exact. Otherwise we get
this panic when running `snforge test --exact`:
```
thread 'main' (4621958) panicked at crates/forge/src/test_filter.rs:64:22:
Argument test_name_filter cannot be None with exact_match
```

## Checklist

- [ ] Linked relevant issue
- [ ] Updated relevant documentation
- [ ] Added relevant tests
- [x] Performed self-review of the code
- [x] Added changes to `CHANGELOG.md`

Co-authored-by: Dariusz Doktorski <dariusz.doktorski@swmansion.com>